### ISSUE TITLE
Does not work on Symfony 4

### ISSUE THREAD

**Issue by byhaskell** [silasjoisten/sonata-multiupload-bundle#56]
Hello. I can not connect the bandl in the four.

```php
->add( 'audio', ModelListType::class, array(
    'label'    => $this->trans( 'object.audio' ),
    'required' => false
), array( 'link_parameters' => array('context' => 'phrases_audio')))
```

I did everything according to the documentation, but after uploading the files they are not attached to the entity, checking the directory in which the file should appear - also not.

**Comment by silasjoisten** [comment]
Hello @byhaskell,
how did you upload your media files? Can you may provide a screenshot?
Its very hard to understand what you mean. May add some screenshots.

**Comment by byhaskell** [comment]
@silasjoisten Yes of course
http://prntscr.com/n4owxp
http://prntscr.com/n4ox3g
http://prntscr.com/n4ox9d
http://prntscr.com/n4oxfj
After closing the pop-up and saving, I check - the files are not uploaded, and of course the media objects are not supported by the entity.
Sorry, that screenshots in another language.

**Comment by silasjoisten** [comment]
@byhaskell 
I see that in the second screenshot you are not using image provider. how does your `config/packages/sonata_media.yaml` look like?

**Comment by byhaskell** [comment]
@silasjoisten 
```
phrases_audio:
            providers:
                - sonata.media.provider.image.phrase

            formats:
                ~
```

sonata.media.provider.image.phrase:
```

namespace App\Application\Sonata\MediaBundle\Provider;

use Sonata\MediaBundle\Provider\FileProvider;
use SilasJoisten\Sonata\MultiUploadBundle\Traits\MultiUploadTrait;

class ImageProvider extends FileProvider
{
	use MultiUploadTrait;
	
}
```

**Comment by silasjoisten** [comment]
And you try to upload an Image. If you configured image provider correctly it should look like:
![Bildschirmfoto 2019-03-29 um 16 32 09](https://user-images.githubusercontent.com/10114981/55243850-4fb29900-5240-11e9-86a2-15a7ddc107d5.png)

**Comment by silasjoisten** [comment]
Try to extend from the ImageProvider of Sonata

```php
namespace App\Application\Sonata\MediaBundle\Provider;

use Sonata\MediaBundle\Provider\ImageProvider;
use SilasJoisten\Sonata\MultiUploadBundle\Traits\MultiUploadTrait;

class ImageProvider extends ImageProvider
{
	use MultiUploadTrait;
	
}

```

**Comment by byhaskell** [comment]
@silasjoisten 
I need a provider for audio files for this, and I use Sonata\MediaBundle\Provider\FileProvider, the name of the classes does not match the reason for testing, I apologize if I confused you with them.

```
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
                - sonata.media.provider.video

            formats:
                small: { width: 100, height: 100, quality: 70}
                big: { width: 500, height: 100, quality: 70}
                meta: { width: 1200, height: 1200, quality: 70}

        meta:
            providers:
                - sonata.media.provider.image

            formats:
                meta: { width: 1200, height: 1200, quality: 70}

        video_cover:
            providers:
                - sonata.media.provider.image

            formats:
                video_cover: { width: 640, height: 488, quality: 70}

        blog:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 335, height: 165, quality: 70}
                big: { width: 975, height: 350, quality: 70}

        trailer:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.video
                - sonata.media.provider.vimeo

            formats:
                trailer:   { width: 1200, height: 1200, quality: 70}

        congratulation_example:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.video
                - sonata.media.provider.vimeo

            formats:
                example: { width: 426, height: 237, quality: 70}

        avatar:
            providers:
                - sonata.media.provider.image

            formats:
                avatar: { width: 100, height: 100, quality: 70}

        logo:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { width: 100, height: 100, quality: 70}
                logo_big: { width: 500, height: 500, quality: 70}
                logo_small: { width: 50, height: 50, quality: 70}

        video_review:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.video
                - sonata.media.provider.vimeo

            formats:
                video_review: { width: 640, quality: 70, resizer: sonata.media.resizer.square}

        how_we_do_it:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.video
                - sonata.media.provider.vimeo

            formats:
                video: { width: 640, quality: 70, resizer: sonata.media.resizer.square}

        examples_video:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.video
                - sonata.media.provider.vimeo

            formats:
                examples_video: { width: 640, quality: 70, resizer: sonata.media.resizer.square}

        placeholder:
            providers:
                - sonata.media.provider.image

            formats:
                ~

        phrases_audio:
            providers:
                - sonata.media.provider.image.phrase

            formats:
                ~

        placeholder_many:
            providers:
                - sonata.media.provider.image

            formats:
                placeholder_many: { width: 100, height: 100, quality: 70}

        placeholder_video:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.video
                - sonata.media.provider.vimeo

            formats:
                video: { width: 1200, height: 1200, quality: 768}

        project:
            providers:
                - sonata.media.provider.file

            formats: ~

        google_api:
            providers:
                - sonata.media.provider.file

            formats: ~

        home_image_header:
            providers:
                - sonata.media.provider.image

            formats:
                ~

        home_image_tablet_header:
            providers:
                - sonata.media.provider.image

            formats:
                ~

        home_image_mobile_header:
            providers:
                - sonata.media.provider.image

            formats:
                ~

        home_image_header_circle:
            providers:
                - sonata.media.provider.image

            formats:
                image: { width: 818, height: 820, quality: 70}

        advantage_icon:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 90, height: 90, quality: 70}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false

    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia

    providers:
        file:
            resizer: false
            service:    sonata.media.provider.file
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'zip']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain', 'application/zip']
        image:
           thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#            thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image
        vimeo:
            thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#           thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image
        youtube:
            thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#           thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image
        dailymotion:
            thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#           thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image
```

**Comment by byhaskell** [comment]
@silasjoisten I will bring order to the types, most likely there screwed up and if there are problems - accomplish your goal, thanks. Confused a little bit.

**Comment by silasjoisten** [comment]
@byhaskell so is this issue closed? Would be great if you you close this.

**Comment by byhaskell** [comment]
```sonata.media.provider.audio.phrase:
        class: App\Application\Sonata\MediaBundle\Provider\AudioProvider
        tags:
            - { name: sonata.media.provider, multi_upload: true }
        arguments:
            - "sonata.media.provider.audio.phrase"
            - "@sonata.media.filesystem.local"
            - "@sonata.media.cdn.server"
            - "@sonata.media.generator.default"
            - "@sonata.media.thumbnail.format"
            - ['mp3']
            - ['audio/mp3']
        public: true```

```
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            phrases_audio:
                providers:
                     - sonata.media.provider.audio.phrase

                 formats:
                     ~```

```
namespace App\Application\Sonata\MediaBundle\Provider;

use Sonata\MediaBundle\Provider\FileProvider;
use SilasJoisten\Sonata\MultiUploadBundle\Traits\MultiUploadTrait;

class AudioProvider extends FileProvider
{
	use MultiUploadTrait;
	
}```
```
->add( 'audio', ModelListType::class, array(
    'label'    => $this->trans( 'object.audio' ),
    'required' => false
), array( 'link_parameters' => array( 'context' => 'phrases_audio' ) ) )```

Now order, but still does not work. I apologize for being initially misleading, the end of the work week affects everyone

**Comment by silasjoisten** [comment]
Does the logs say anything?

**Comment by silasjoisten** [comment]
I think your issue is not related to this bundle but i tried to reproduce it. Feel free to use it:
```twig
{# templates/Media/Provider/audio_thumbnail.html.twig #}
<i class="fa fa-file-audio-o fa-5x"></i>
```

```twig
{# templates/Media/Provider/view_audio.html.twig #}
<audio controls>
    <source type="{{ media.contenttype }}" src="{% path media, 'reference' %}"/>
</audio>
```

```php
// App\Application\Sonata\MediaBundle\Provider\AudioProvider.php
<?php

namespace App\Application\Sonata\MediaBundle\Provider;

use SilasJoisten\Sonata\MultiUploadBundle\Traits\MultiUploadTrait;
use Sonata\MediaBundle\Provider\FileProvider;
use Sonata\MediaBundle\Provider\Metadata;

class AudioProvider extends FileProvider
{
    use MultiUploadTrait;

    public function getProviderMetadata()
    {
        return new Metadata($this->getName(),
            $this->getName().'.description',
            null,
            'SonataMediaBundle',
            ['class' => 'fa fa-file-audio-o']
        );
    }
}
```

```yaml
# config/services.yaml
    sonata.media.provider.audio:
        class: App\Application\Sonata\MediaBundle\Provider\AudioProvider
        tags:
            - { name: sonata.media.provider, multi_upload: true }
        arguments:
            - "sonata.media.provider.audio"
            - "@sonata.media.filesystem.local"
            - "@sonata.media.cdn.server"
            - "@sonata.media.generator.default"
            - "@sonata.media.thumbnail.format"
            - ['mp3', 'mp4', 'wav']
            - []
            - '@sonata.media.metadata.proxy'
        calls:
            - [ setTemplates, [ { helper_thumbnail: "Media/Provider/audio_thumbnail.html.twig", helper_view: "Media/Provider/view_audio.html.twig" } ] ]
        public: true
```

```yaml
# config/packages/sonata_media.yaml
sonata_media:
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: App\Application\Sonata\ClassificationBundle\Entity\Category

    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                # ...
                - sonata.media.provider.audio
    # ...
```

```yaml
# translations/SonataMediaBundle.en.yaml
sonata.media.provider.audio: Audio

```
