### ISSUE TITLE
Can't get it to work SF4

### ISSUE THREAD

**Issue by anitaeisenhaber** [silasjoisten/sonata-multiupload-bundle#62]
Hello,
I am trying to get this to work but am a little bit stuck.
```
// App\Application\Sonata\MediaBundle\Provider\MultiImageProvider.php
<?php

namespace App\Application\Sonata\MediaBundle\Provider;

use SilasJoisten\Sonata\MultiUploadBundle\Traits\MultiUploadTrait;

class MultiImageProvider extends \Sonata\MediaBundle\Provider\FileProvider
{
    use MultiUploadTrait;
}
```

```
// config/services.xml
  <service id="sonata.media.provider.multi_image" class="App\Application\Sonata\MediaBundle\Provider\MultiImageProvider" public="true">
            <tag name="sonata.media.provider" multi_upload="true"/>
            <argument>sonata.media.provider.multi_image</argument>
            <argument type="service" id="sonata.media.filesystem.local"/>
            <argument type="service" id="sonata.media.cdn.server"/>
            <argument type="service" id="sonata.media.generator.default"/>
            <argument type="service" id="sonata.media.thumbnail.format"/>
        </service>
```

```
// config/packages/sonata_media.yaml
sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            download:
                strategy: App\Security\Media\DownloadStrategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
                - sonata.media.provider.multi_image
```

```
//Admin Class
$form->add('media', MediaType::class, [
            'provider' => 'sonata.media.provider.multi_image',
            'context' => 'default',
            'data_class' => 'App\Application\Sonata\MediaBundle\Entity\Media',
            'required' => true,
        ]);
```
The upload is still the same and I feel like I am doing something really basic wrong or missing something. How do I get my form to display the multiupload instead of normal upload?

**Comment by silasjoisten** [comment]
@anitaeisenhaber sorry for the delay. Thanks for the detailed information.
1. You don't need to create a custom Provider. Just override the existing `ImageProvider` of sonata.
It can look like this:
```php
<?php
//App\Application\Sonata\MediaBundle\Provider\ImageProvider.php
namespace App\Application\Sonata\MediaBundle\Provider;

use SilasJoisten\Sonata\MultiUploadBundle\Traits\MultiUploadTrait;
use Sonata\MediaBundle\Provider\ImageProvider as BaseImageProvider;

class ImageProvider extends BaseImageProvider
{
    use MultiUploadTrait;
}
```
Your yaml should look like:

```yaml
parameters:
    sonata.media.provider.image.class: App\Application\Sonata\MediaBundle\Provider\ImageProvider

services:
    sonata.media.provider.image:
        class: "%sonata.media.provider.image.class%"
        arguments:
            - "sonata.media.provider.image"
            - "@sonata.media.filesystem.local"
            - "@sonata.media.cdn.server"
            - "@sonata.media.generator.default"
            - "@sonata.media.thumbnail.format"
            - ['jpg', 'png', 'jpeg', 'gif']
            - ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png', 'image/gif']
            - "@sonata.media.adapter.image.default"
            - "@sonata.media.metadata.proxy"
        calls:
            - [ setTemplates, [ { helper_thumbnail: "Media/Provider/thumbnail.html.twig", helper_view: "Media/Provider/view_image.html.twig"} ] ]
        tags:
            - { name: sonata.media.provider, multi_upload: true }
        public: true
```
 This is almost the same like yours with a few small differences regarding the classname.

This bundle does not provide a form type. It only hooks into the `select_provider.html.twig` and links to an multiupload action so you can access the multi upload page via. `new`button in list view.

What you could do is generate an url to the multiupload action.
